[package]
name = "Student_NFT_Avatar_Generator–Rewarded_for_completion"
version = "1.0.0"
authors = []

[addresses]
MyModule = "9706d4116f83f9701aaee780d6d046088a159c8934492b3a8b5eb28ee55faa32"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dev-dependencies]
